server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8080
spring:
  application:
    name: SecurityR
  threads:
    virtual:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    enabled: true
  datasource:
      url: jdbc:sqlserver://172.16.32.181:1433;databasename=R;encrypt=true;trustServerCertificate=true
      username: R
      password: R
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
          pool-name: MyBatisHikariCP
          maximum-pool-size: 10
          minimum-idle: 5
          idle-timeout: 30000
          max-lifetime: 600000
          connection-timeout: 30000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.reyes.securityr.model
  mapper-locations: classpath*:mappers/*.xml
